### ISSUE TITLE
Application error reporting and monitoring

### ISSUE THREAD

**Issue by tekin** [dxw/dfe-teachers-payment-service#17]
So that we know when some aspect of the service is broken or isn't working as expected and so can have insight into these runtime errors when they happen to make them easier to resolve, we want to add error reporting and monitoring to the application. This will take the form of a third party service such as Sentry, or Rollbar (actual service TBC after consulting with DfE tech folks)

Note that once we move to the Azure platform we may be able to use [Azure Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview) for this.

**Comment by mec** [comment]
Gone with Rollbar for this. We can use the  Heroku add-on whilst we are on Heroku.
